# Generated by Django 3.1.3 on 2020-11-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='product',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='image_url_1',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='image_url_2',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='image_url_3',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='image_url_4',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='image_url_5',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
