# Generated by Django 3.1.3 on 2020-11-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('star', models.CharField(blank=True, choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
