# Generated by Django 3.1.3 on 2020-11-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20201117_2029'),
    ]
