# Generated by Django 3.1.3 on 2020-11-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20201117_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.CharField(blank=True, choices=[('1', 'one'), ('222', '2'), ('33', '31'), ('4', '4'), ('5', '5')], max_length=10),
        ),
    ]
