# Generated by Django 3.1.3 on 2020-11-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='color',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
