# Generated by Django 3.1.3 on 2020-11-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201117_1958'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderlist',
            table='order_lists',
        ),
    ]
