# Generated by Django 3.1.3 on 2020-11-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201122_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='color',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
